# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build

- stage: test
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Test
    
- stage: staging
  dependsOn: test
  jobs:
  - job: deploy_staging
    pool:
      vmImage: 'Ubuntu 16.04'
    displayName: ebiiiiii
    enviroment: Staging
    strategy:
        runOnce:
            deploy:
                steps:
                    - script: echo this is ebiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii 
    steps:
    - script: echo Staging

- stage: prod
  dependsOn: staging
  jobs:
  - job: deploy_prod
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Prod